#!/bin/sh
# Example script to open websites in a preferred browser

# This is for my window manager
lsgrp 2 | xargs mapw -u &>/dev/null

run_youtube() {
	if pgrep idiotbox; then
		st -c w3m -e w3m http://127.0.0.1:8080
	else
		run_chrome "$@" &
	fi
}

## main
case "$@" in
	*google*) chromium "$@" & ;;
	*photos.app.goo.gl*) chromium "$@" & ;;
	*youtube*) run_youtube "$@" & ;;
	*twitch*) chromium "$@" & ;;
	*t.co*) chromium "$@" & ;;
	*twitter*) chromium "$@" & ;;
	*discord*) chromium "$@" & ;;
	*) luakit "$@" &>/dev/null & ;;
	
esac
